server.port=8081
spring.application.name=redis
# Endereço do Docker (localhost se estiver na mesma máquina)
spring.data.redis.host=redis-lab
# Porta padrão que mapeamos no comando 'docker run'
spring.data.redis.port=6379